### ISSUE TITLE
Output: Reconsider option to write output to a file

### ISSUE THREAD

**Issue by rsenden** [fortify-ps/fcli#101]
Do we really need to provide an option for writing the output to a file, or can we just rely on shell redirection? The `-o` option was based on the similar `curl` option, but looking at for example `kubectl`, it doesn't seem to provide any options for writing output to a file. Instead, it uses the `-o`/`--output` options to specify the output format (similar to our `--fmt` option). If we don't provide an option for writing to a file, we could use the `kubectl` approach of having a `-o`/`--output` option to specify the output format.

**Comment by wtfacoconut** [comment]
Personally, I think the `-o/--ouput` is fine.
But I will admid that I can only think of one scenario where the `-o` option might be a nicer option to have over shell redirection.

If we keep it around, do you think it will end up as useless technical debt? If not, then I'd just say keep it to give the user an explicit option to use.

**Comment by rsenden** [comment]
What's the one scenario where `-o` might be a nicer option than shell redirection? The advantage of removing this option is that we can use `-o` to specify output format; `-o json` looks better than `--fmt json` and is more consistent with for example `kubectl`.

**Comment by wtfacoconut** [comment]
The one nice thing I was referring to is that with the `-o` we can choose to not create a file under some situations. Why would we want to do that? With fcli, I can think of two things could possibly occur:
  - Either "No data" is sent to stdout, which if redirected, will result in file creation with that as its' contents.
  - Or an exeption of some kind will be thrown, where if redirection is used, this will cause an empty file to be created.
 
With shell/scripting, I think it's a common practice to test to see if a file exists.

Granted, someone could also very easily just check the file to see if the first line has the the text "No data" or if it's empty or even check the exit code of fcli, but I think it would be better if the file was not even created in the event of an exception or no-data being retrieved.

**Comment by rsenden** [comment]
Option names have been updated:
- `-o | --output` now specifies output format
- `--output-to-file` now allows for specifying an output file. Since this option will likely not be used much, we don't mind the long option name
