### ISSUE TITLE
Output: Review `--json-path` option

### ISSUE THREAD

**Issue by rsenden** [fortify-ps/fcli#102]
With the current help text, it's not clear what data the provided JSON path actually operates on (i.e. does it operate on the full REST response, or on the `data` object inside the response?). Also, the option name may leave users thinking that this option only applies to JSON output, which is not the case. For example, the `--json-path` can also be used for advanced client-side filtering of the output when using `table` or `csv` output formats.

Suggestions on how to improve this are welcome.

**Comment by wtfacoconut** [comment]
How do you feel about renaming the option to `--filter-exp` and just mention that the option "Expects a JSON path expression that will be applied regardless of output format chosen"?

**Comment by rsenden** [comment]
`--filter-exp` could be an option, but I guess you can also do many other things apart from filtering with a JSON path expression...

**Comment by wtfacoconut** [comment]
Other name ideas:
- --process-exp
- --query-exp
- --query
- --advanced-exp
- --expression
-

**Comment by rsenden** [comment]
For now, the `--json-path` option has been removed, as most of the functionality can be achieved using other options.
