### ISSUE TITLE
Consistency: Should we keep "get" commands?

### ISSUE THREAD

**Issue by wtfacoconut** [fortify-ps/fcli#103]
For the vast majority of situations, the `list` commands of entities can basically provide the same information as a `get` command. Because of that, there is some internal debate as to wether or not to keep `get` commands around as it's currently a bit of a redundant capability.

At the moment, three potential advantages of get commands:

-  We can provide a different default output format, i.e. tree or yaml, such that the user gets more details on the get command. However, you can get (almost) the same with 'list --id .. --fmt tree'
-  The list command returns an array, whereas the get command returns a single entry; if you want to do any further processing on the output, then having a single object might be slightly easier than an array
- one more potential advantage; on the get command we could add options for embedding additional data, which doesn't make too much sense for list commands
  - For example, 'ssc appversion get myApp:myVersion --include-attrs --include-users'
  - You wouldn't be able to properly display such embedded (arrays of) entities in table output, so wouldn't make much sense to have those options on the list command

**Comment by wtfacoconut** [comment]
+1 for dropping get commands. Because the `list` command can essentially retrieve the same information provided that something like the `--id` option is used, I just don't think that it adds enough value and benefit to the user experience to justify maintaining many get commands.

**Comment by rsenden** [comment]
I wasn't a big fan of `get` commands either and for now have mostly skipped creating them, but I think they would actually make sense (at least in some cases). As an example:
- `fcli ssc appversion get myApp:myVersion`, with single object output
- `fcli ssc appversion list --applicationName myApp --name myVersion --fmt tree`, with single entity embedded in array/list

The `get` command looks much friendlier for average `fcli` users, and the output would be (slightly) easier to process in automation scenarios (mostly applicable if the user chooses json or yaml outputs, piping the output to something like `jq` for example). 

The `list` command could potentially be shortened by allowing something like the following:
- `fcli ssc appversion list --appversion myApp:myVersion --fmt tree`

However, this command:
- Is still more difficult to use (more typing) than the `get` command
- It doesn't really make much sense to `list` a single application version; you are basically embedding a `get` command inside the `list` command, most likely complicating the code for the `list` command

Also, in general, `get` commands should be relatively easy to implement; in general they would just:
- Set the default output format to `tree`
- Have a single positional 'name or id' parameter, for which we already have mixins that allow for resolving this to an id
- Invoke a single REST endpoint
- Output the results

We could even create an `Abstract<system>GetCommand` similar to `AbstractSSCTableOutputCommand` that takes care of setting the default output format, and writing the output.

All of the above, combined with potential other advantages of a dedicated `get` command, like the ability to provide command line options for including data from other (sub-)entities (i.e. `fcli ssc appversion get myApp:myVersion --include-attributes`), makes me think that `get` commands may not be a bad idea after all.

**Comment by rsenden** [comment]
Of course, the ability to implement proper `get` commands requires #104 to be fixed; until this is fixed we could default to `yaml` output instead, which is slightly less human-readable due to mark-up.

**Comment by wtfacoconut** [comment]
Even though I'm still not personally a fan of the `get` commands, I am open to keeping them around. And you are right, the `get` command usually doesn't require much code to create and maintain.

I do have one question though. Wouldn't it feel weird that the `get` command is outputting information by default in the `tree` format while all other commands output in a `table`? It just feels a bit odd and inconsistent. 

But I guess if the idea is that the purpose of the `get` command is to provide **full** detailed information about an entity instance, then, okay, I guess that works too.

**Comment by rsenden** [comment]
The whole idea of the `get` command is to display the details for a single entity, somewhat similar to the `docker inspect` command, so I'd actually expect this to return the output in `tree` format rather than `table` format. We could also use `inspect` instead of `get` to be consistent with `docker inspect`, but I like `get` better as it's shorter and also properly describes the behavior.

**Comment by wtfacoconut** [comment]
Okay. So I guess that we agree to keep around the `get` commands with the intent that it will provide full information on an entity instance in a similar fashion as the `docker inspect` command.
