### ISSUE TITLE
Support login to SSC & FoD

### ISSUE THREAD

**Issue by wtfacoconut** [fortify-ps/fcli#11]
Support login to SSC & FoD with the additional capabilities:

- auto login renewal 
- auto encryption of sensitive data. (eg: credentials, api tokens)
- switch login sessions

**Comment by rsenden** [comment]
Basic functionality done, dependent on #19 for secure session storage.

**Comment by rsenden** [comment]
Login and logout operations for SSC & FoD have been implemented
