### ISSUE TITLE
Bug: `fcli --version` doesn't output anything

### ISSUE THREAD

**Issue by rsenden** [fortify-ps/fcli#112]
Currently `fcli --version` doesn't output anything; it should output a proper version number.

We should consider a similar approach as for `FortifyVulnerabilityExporter`, where a version number is generated during pipeline execution (matching the actual version tag for release builds, or based on branch and date/time for non-release builds) and passed to the gradle build, as shown here: https://github.com/fortify/FortifyVulnerabilityExporter/blob/13e2856137507c2384935c885371ea892269b7c3/.github/workflows/ci.yml#L75

The Gradle build should then properly store the provided version number for use by the `fcli --version` command.

**Comment by rsenden** [comment]
Current implementation works for jar version, but not native images

**Comment by wtfacoconut** [comment]
For some reason, I'm seeing this again with our native binaries for both v1.0 and v1.0.1.
This was reported by QA.

**Comment by rsenden** [comment]
This issue was reintroduced because we now automatically generate resource-config.json files (required for native binaries) during the Gradle build, based on resource files found in src/main/resources. Since the build properties file is being generated during the build, it wasn't being picked up by the automated resource-config.json generation. I've updated the build properties generation task to also generate a corresponding resource-config.json file.
