### ISSUE TITLE
SSC: Reconsider --from, --for, --to, ... options for specifying appversion

### ISSUE THREAD

**Issue by rsenden** [fortify-ps/fcli#116]
Even as an `fcli` developer, I often forget which variant to use, and sometimes we may even be using the wrong option name. For example, is it `fcli ssc appversion-user list --from ...` or `fcli ssc appversion-user list --for ...`? In the end, I often just revert to using the longer `--appversion` option to avoid having to look at the command help to identify what option name to use.

Even though grammatically less attractive, maybe we should just stick to one option name `--appversion`, probably with a short alias like `--av`. We could then also consider re-adding the `av-*` command aliases for consistency, so you'd use commands like `fcli ssc av-user list --av ...` as the short variant, or `fcli ssc appversion-user list --appversion ...` as the long variant.

**Comment by wtfacoconut** [comment]
+1 for standardizing on `--appversion`.

**Comment by rsenden** [comment]
This has been implemented
