### ISSUE TITLE
SC-DAST: Support polling/waiting of SC-DAST scan to complete to auto retrieve scan status

### ISSUE THREAD

**Issue by wtfacoconut** [fortify-ps/fcli#13]
Support polling/waiting of SC-DAST scan to complete to auto retrieve scan status

**Comment by rsenden** [comment]
I think this is mostly implemented, but:
- We should review for which commands it makes sense to have this functionality
- We should decide on standard option names across all modules and commands; current SC-DAST commands use `--wait` or `-w`, but we might want to consider `--block` instead (as this is also used by ScanCentral Client, and 'block' is more commonly used, as in 'blocking a pipeline'

**Comment by rsenden** [comment]
Implemented through the `wait-for` command
