### ISSUE TITLE
--output help text: output format ordering

### ISSUE THREAD

**Issue by young-s-park** [fortify-ps/fcli#146]
Current help text has the format options ordered like:
-o, --output=format[=<options>]
                             Output format: **json, json-flat, yaml, yaml-flat, table, table-plain, tree, tree-flat, xml, xml-flat, csv, csv-plain, expr, json-properties**. The 'json-properties'...

Can we make this alphabetical order?

**Comment by rsenden** [comment]
We should be able to re-order these, and I agree that for the 'standard' output formats, it would be better to put them in alphabetical order. However, `expr` and `json-properties` are somewhat special formats, hence they were listed last to separate them from the 'standard' formats. Based on this information, do you still think that all formats should be in alphabetical order?

**Comment by young-s-park** [comment]
Thanks for the explanation. I think it's fine to keep the "special" formats listed last, while the "standard" are in alphabetical order.
