### ISSUE TITLE
SSC: --token synopsis on ssc session login command doesn't show value

### ISSUE THREAD

**Issue by young-s-park** [fortify-ps/fcli#153]
What is the proper way to supply the SSC token for the 'ssc session login --token'? The help message shows:
![image](https://user-images.githubusercontent.com/48065971/201408962-47ada8f9-4da5-40a9-8cd0-15b9861fbc5f.png)

It doesn't specify that you need to (or how to) pass the token value.

Expected:
-t,--token \<token\> OR -t,--token=\<token\>

Similar issue with sc-sast session login --ci-token
![image](https://user-images.githubusercontent.com/48065971/201409820-fc9678c4-44bb-425b-afd0-4c2e7203dac4.png)

**Comment by young-s-park** [comment]
Oops, I think this is user error. I guess it just prompts you for the token if you use the -t,--token option. Is there an option to supply the token value to bypass this prompt?

**Comment by rsenden** [comment]
It should be possible to supply the token using -t <token> or --token=<token> (or other variants); we'll need to check why this isn't properly shown in the help output
