### ISSUE TITLE
fcli ssc app update : no application found for application name

### ISSUE THREAD

**Issue by james-du1** [fortify-ps/fcli#166]
when using the application name as the identifier to do a application name update, exception occurred saying application NOT FOUND, but the application name was updated. issue is NOT reproduced IF application ID was used

![image](https://user-images.githubusercontent.com/120057653/206289406-ba90e9b9-51fd-4b8c-b64c-c14f6d4bcb74.png)

**Comment by xakrurychle** [comment]
fixed in v1.0.1
