### ISSUE TITLE
fcli ssc app delete : unable to delete application versions IF session was created using -t

### ISSUE THREAD

**Issue by james-du1** [fortify-ps/fcli#169]
fcli ssc app delete : unable to delete application versions IF session was created using -t
note: IF -u and -p was used instead of -t, user is able to delete application versions successfully

![image](https://user-images.githubusercontent.com/120057653/206301554-cd9037b0-4fd1-491b-8a69-449067358421.png)

**Comment by wtfacoconut** [comment]
Hello @james-du1 . Thanks for the testing contributions.  😊

Can you verify very quick what kind of API token you used to create the session? Was it the unified login token, cicd toke , or something else?

If possible, can you try to rerun the test using the unified login token?

**Comment by james-du1** [comment]
@wtfacoconut 
sorry,  an incorrect token was used to create the session, using the unified login token works fine
