### ISSUE TITLE
fcli ssc issue-template create : new default template status is not reflected after creating the new project template with --set-as-default

### ISSUE THREAD

**Issue by james-du1** [fortify-ps/fcli#180]
fcli ssc issue-template create : new default template status is not reflected after creating the new project template with --set-as-default

note: in ssc the issue template is set to default, but it's Not displayed in the response after running the command

![image](https://user-images.githubusercontent.com/120057653/207198092-9d6e51b9-d823-44d9-a840-795c7688305c.png)

**Comment by xakrurychle** [comment]
fixed in v1.0.1
