### ISSUE TITLE
fcli ssc issue-template update : exception occurred after updating the issue template

### ISSUE THREAD

**Issue by james-du1** [fortify-ps/fcli#181]
seems like there could be some logical issues with the response after running the command

after the command was ran, it is still looking for the UNMODIFIED issue template name, it should look for the UPDATED one instead

![image](https://user-images.githubusercontent.com/120057653/207199190-704d75ea-5d17-4d9e-a0b9-027f28091050.png)

**Comment by xakrurychle** [comment]
fixed in v1.0.1
