### ISSUE TITLE
fcli ssc token update - enhancement documentation

### ISSUE THREAD

**Issue by xakrurychle** [fortify-ps/fcli#195]
change the synopsis <token> to <tokenId>

fcli ssc token update -p[=<password>] [--description=<description>] [--expire-in=<expireIn>] -u=<user> [[-h] [--env-prefix=<envPrefix>] [--log-file=<logFile>] [--log-level=<logLevel>]] [--session=<sessionName> | [--url=<url> [-k]]] ] [--store=_variableName[=<propertyNames>]] [--output-to-file=<outputFile>]] <token>

**Comment by rsenden** [comment]
Already fixed as part of 8e8b9243b591c5104117faf11ad75b70c4e6deba
