### ISSUE TITLE
fcli ssc token update - response - Token N/A // MAC

### ISSUE THREAD

**Issue by xakrurychle** [fortify-ps/fcli#196]
qaprague@Jacks-Mac-mini ~ % fcli ssc token update  -u name -p pass --expire-in 6h --description desc --url https://qa-st-c7-kho01.prgqa.hpecorp.net:8443/ssc 74
 Id  Token  Creation date                  Terminal date                  Remaining usages  Type     Description       Username  Href
 74  N/A    2022-12-14T11:42:04.003+00:00  2022-12-14T17:44:29.185+00:00  -1                CIToken  desc  krystof   https://qa-st-c7-kho01.prgqa.hpecorp.net:8443/ssc/api/v1/tokens/74

**Comment by rsenden** [comment]
The update command can't display the token (as SSC doesn't return it on update operations); this column was already removed from the output in 35523cc2066c289802d2dc4bda7f4c01cbcbe554 so closing this issue.
