### ISSUE TITLE
Help usage is incorrect for getting help about specific commands

### ISSUE THREAD

**Issue by karenewlees** [fortify-ps/fcli#217]
I typed: fcli -h and the usage statement provided is: 
Usage: fcli [-V] [[-h] [--env-prefix=<envPrefix>] [--log-file=<logFile>] [--log-level=<logLevel>]] [COMMAND]

Following the usage description, I typed: fcli -h tool, but this gave me the same help content as the first command: fcli -h.

I then tried: fcli tool -h and this command gave me information about the tool command.

The usage statement is incorrect. However, it seems more logical to type: fcli -h <command> to get help on a command. IMHO
fcli version 1.0.4, built on 2023-01-05 11:51:09

**Comment by rsenden** [comment]
I guess this is a matter of interpretation/expectation. The help output displays the following:

```
Generic fcli options:
  -h, --help                 Show this help message and exit
```

So, this states that the `-h` option displays this help message only; there is no mention that this option can be used for displaying help for sub-commands. If that had been the case, it would probably also have been more logical if the synopsis had shown something like `[-h [command]]` to explicitly state that the help option supports an argument specifying for which command you'd want to display the help information.

This behavior is consistent with other commonly used CLI tools, for example `kubectl -h create` displays the help output for the top-level `kubectl` command; you'd need to use `kubectl create -h` to display the help output for the `create` command.

So, this is working as designed, but I'll update the description for the `-h` option to make it more clear how to obtain help for sub-commands.

**Comment by karenewlees** [comment]
Thanks for considering and updating the description. My expectation was that it works similar to SC SAST CLI which specifies that you type scancentral -h <command> to get help with the specific <command>.
