### ISSUE TITLE
Remove incorrect `@Inject` annotations

### ISSUE THREAD

**Issue by rsenden** [fortify-ps/fcli#25]
The `SCDastScanActionsHandler` class contains a `UnirestInstance` field annotated with `@Inject`, however it seems like this field is not meant to be injected by Micronaut's dependency injection mechanism, but rather is supposed to be provided as a constructor parameter by the caller of this class. As such, the `@Inject` annotation is not applicable here and should be removed. It should be verified whether there are any inappropriate annotations in any of the other classes.

**Comment by Andhrei** [comment]
fixed by Ruud
