### ISSUE TITLE
Code quality: Add request parameters using unirest.routeParam() instead of string concatenation

### ISSUE THREAD

**Issue by Andhrei** [fortify-ps/fcli#27]
as seen in https://github.com/fortify-ps/fcli/blob/3279ccec8bb97c8af43caa5ece0d2f8ab2bc9a73/fcli-ssc/src/main/java/com/fortify/cli/ssc/picocli/command/crud/get/version/SSCGetVersionAttributesCommand.java#L55

**Comment by rsenden** [comment]
Removed 'bug' label, as this is not really a bug but just a possible code improvement without any functional impact.

**Comment by rsenden** [comment]
Should now have been implemented wherever appropriate; in some places we still use string concatenation/replacement for valid reasons
