### ISSUE TITLE
SC-SAST: Implement proper session management

### ISSUE THREAD

**Issue by rsenden** [fortify-ps/fcli#75]
Commands in the sc-sast module may call both SSC and SC SAST Controller endpoints, requiring different authentication tokens. In addition, for submitting scan requests we also need to pass a ScanCentralCtrlToken or CIToken. We need to decide on what the 'sc-sast session login' command should look like, how to handle the different tokens (persist in session, persist across sessions), ...

**Comment by wtfacoconut** [comment]
Current implementation works, so I'm assigning this to a later milestone unless you see some other major issue.

**Comment by rsenden** [comment]
Current implementation works for very basic interaction with the controller, but for example won't allow for starting scans (as there's no ScanCentralCtrlToken) and doesn't have support for any of the SSC endpoints related to SC SAST (as there's no UnifiedLoginToken). So, if we want to have any proper SC SAST functionality, we must first improve session management to add support for these other tokens.
________________________________

**Comment by wtfacoconut** [comment]
Understood. Moving to v1.0 release milestone.

**Comment by rsenden** [comment]
Implemented
