### ISSUE TITLE
Output: Improve or remove filtering on date/time fields

### ISSUE THREAD

**Issue by rsenden** [fortify-ps/fcli#76]
Current filtering functionality requires exact date/time to be specified, which obviously isn't useful. Preferably, we should support more advanced filtering on date/time fields, like last 7 days, everything older than 7 days, everything older than specific date, everything newer than specific date, everything on a specific date (regardless of time).

Until we implement such functionality, we can mark all filtering options that act on date fields as hidden, thereby still allowing for `@AddAsDefaultColumn` to be used.

**Comment by wtfacoconut** [comment]
Important, but not critical. Will recommend detering to a later release.

**Comment by rsenden** [comment]
Not really relevant anymore, as we no longer have dedicated filtering options for each output field, but rather a single `-q | --query` option. For now, this option still incurs the same issue as it only allows for equals filtering, but adding date/time filtering is part of general improvements to this query option.
