### ISSUE TITLE
Code Quality: Review SC DAST module

### ISSUE THREAD

**Issue by rsenden** [fortify-ps/fcli#78]
SC DAST commands seem to use a somewhat different code structure compared to other modules, for example there are many 'Handler' classes that don't exist in other modules. For consistency, we should review this module, and refactor as necessary. We should also make sure that command and CLI option structure is consistent with other modules.

**Comment by wtfacoconut** [comment]
Current implementation does work. Code refactor should probably be defered to a later release.

**Comment by rsenden** [comment]
Indeed it's already functional, but this could potentially cause changes to the `sc-dast` commands (for example if we make changes to the command tree, change option names to make them consistent with SSC/SC-SAST module, ...), requiring users to change their pipelines if they have already started using this functionality. So, if possible, we should try to get this in before an official v1 release.

**Comment by wtfacoconut** [comment]
Understood. Then, as you've already mentioned, we should at minimum agree on:

- Command structure
- Options/Option Names for all existing sc-dast commands
- How to handle sessions

## Command structure:
- I currently have no major issues with the currently command structure of the sc-dast module. The only things that feels a bit off is the entity name `scan-output`, but I think my feelings here can be alleviated by updating the help message.

## Options/Option Names for all existing commands:
- Many of the options have two or more aliases. I think we can probably limit all options to having at most, one alias. Examples are:
- `-i, --id, --scan-id=<scanId>`
- `-w, --wait, --wait-completed`
- `-f, --file, --output-file=<file>`
- `-s, --settings, --settings-id, --settings-identifier`
- `-M, --mode, --scan-mode=<scanMode>`
- `-U, --url, --start-url=<startUrls>`
- `-P, --policy, --policy-id=<policyId>`

## How to handle sessions
- This is being handled in issue #74
