### ISSUE TITLE
Output: Merge `--flatten` and `--[no-]headers` with `--fmt` in OutputMixin

### ISSUE THREAD

**Issue by rsenden** [fortify-ps/fcli#99]
`OutputMixin` currently provides the following three options:
- `--fmt`
- `--flatten`
- `--[no-]headers`

However, `--flatten` is ignored for CSV and table outputs (as these output formats are always flattened), and `--[no-]headers` is ignored for all output formats except CSV and table. We should consider condensing these into a single `--fmt` option that provides these options as separate output formats, i.e. `--fmt=`:
- `json`
- `json-flat`
- `yaml`
- `yaml-flat`
- `table`
- `table-plain` (no headers)
- `csv`
- `csv-plain`
- ...

Any suggestions for better names for these formats are welcome. Also, not 100% sure whether we can use dashes in the format names, as these will map to enum values (need to check picocli).

**Comment by wtfacoconut** [comment]
How do you feel about `table-headless` and `csv-headless`, instead of `table-plain` and `csv-plain`?

**Comment by rsenden** [comment]
Implemented, using the originally suggested format names.
